#!/bin/bash
# Phone Link equivalent for Deepin: screen mirroring and full control of the
# phone from the desktop, over USB or (later) Wi-Fi.
#
# Installs scrcpy from the upstream prebuilt release, pinned by version and
# SHA-256. The prebuilt binary is statically linked against SDL and ffmpeg and
# needs only libc/libudev/libcap, so this pulls in no apt packages at all and
# cannot disturb Deepin's own libraries.
#
# Everything lands under $HOME except one udev rule, so the only sudo prompt is
# for that rule. Safe to re-run; it reconciles every step on each invocation.

set -euo pipefail
cd "$(dirname "$0")"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
step() { echo -e "\n${BLUE}==>${NC} $1"; }
ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
die()  { echo -e "  ${RED}✗${NC} $1" >&2; exit 1; }

# Pinned upstream release. To upgrade, bump both values together — the checksum
# is published by upstream in SHA256SUMS.txt alongside the tarball.
SCRCPY_VERSION="4.1"
SCRCPY_SHA256="ad56ae8bfeedf41e824945c11dbf55fcb092b3e615b9b486f48a50e30d389635"
SCRCPY_TARBALL="scrcpy-linux-x86_64-v${SCRCPY_VERSION}.tar.gz"
SCRCPY_URL="https://github.com/Genymobile/scrcpy/releases/download/v${SCRCPY_VERSION}/${SCRCPY_TARBALL}"

OPT_DIR="$HOME/.local/opt"
INSTALL_DIR="$OPT_DIR/scrcpy-${SCRCPY_VERSION}"
BIN_DIR="$HOME/.local/bin"
UDEV_RULE="/etc/udev/rules.d/51-android.rules"

# --- 1. Prerequisites --------------------------------------------------------
step "Checking prerequisites"
[ "$EUID" -ne 0 ] || die "do not run this as root — it installs into \$HOME (it will sudo only for the udev rule)"
[ "$(uname -m)" = "x86_64" ] || die "this pins the x86_64 build; you are on $(uname -m)"
command -v curl >/dev/null || die "curl is not installed"
command -v tar  >/dev/null || die "tar is not installed"
ok "x86_64, curl and tar present"

case ":$PATH:" in
    *":$BIN_DIR:"*) ok "$BIN_DIR is on PATH" ;;
    *) warn "$BIN_DIR is not on PATH — add it to ~/.zshrc:"
       echo "      export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

# --- 2. Install scrcpy -------------------------------------------------------
step "Installing scrcpy $SCRCPY_VERSION"
if [ -x "$INSTALL_DIR/scrcpy" ]; then
    ok "already installed at $INSTALL_DIR"
else
    mkdir -p "$OPT_DIR"
    TMP="$(mktemp -d)"
    trap 'rm -rf "$TMP"' EXIT

    echo "  downloading $SCRCPY_TARBALL ..."
    curl -sSL --fail -o "$TMP/$SCRCPY_TARBALL" "$SCRCPY_URL" \
        || die "download failed — check connectivity"

    # Verify before extracting. A mismatch means a corrupted download or a
    # tampered release; either way we must not unpack it.
    echo "$SCRCPY_SHA256  $TMP/$SCRCPY_TARBALL" | sha256sum -c --quiet - \
        || die "SHA-256 mismatch — refusing to install"
    ok "checksum verified"

    tar xzf "$TMP/$SCRCPY_TARBALL" -C "$TMP"
    rm -rf "$INSTALL_DIR"
    mv "$TMP/scrcpy-linux-x86_64-v${SCRCPY_VERSION}" "$INSTALL_DIR"
    chmod +x "$INSTALL_DIR/scrcpy" "$INSTALL_DIR/adb"
    ok "unpacked to $INSTALL_DIR"

    rm -rf "$TMP"; trap - EXIT
fi

# --- 3. Launchers ------------------------------------------------------------
# scrcpy needs to find scrcpy-server and an adb binary. Rather than rely on
# path-relative lookup surviving a symlink, point at both explicitly.
step "Creating launchers in $BIN_DIR"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/scrcpy" <<EOF
#!/bin/sh
# Generated by setup-phone-link.sh — do not edit; re-run the script instead.
export SCRCPY_SERVER_PATH="$INSTALL_DIR/scrcpy-server"
export ADB="$INSTALL_DIR/adb"
exec "$INSTALL_DIR/scrcpy" "\$@"
EOF
chmod +x "$BIN_DIR/scrcpy"
ok "scrcpy"

cat > "$BIN_DIR/adb" <<EOF
#!/bin/sh
# Generated by setup-phone-link.sh — do not edit; re-run the script instead.
exec "$INSTALL_DIR/adb" "\$@"
EOF
chmod +x "$BIN_DIR/adb"
ok "adb (bundled $("$INSTALL_DIR/adb" version 2>/dev/null | head -1 | awk '{print $NF}'))"

# --- 4. udev rule ------------------------------------------------------------
# Without this, adb sees the phone as "no permissions" unless run as root.
# TAG+="uaccess" hands the device to whoever is logged in at the seat, which
# avoids having to manage a plugdev group membership.
step "Installing udev rule for Android devices"
RULE_CONTENT='# Installed by setup-phone-link.sh — Android ADB access for the logged-in user.
# 04e8 = Samsung. Add further idVendor lines here for other phone makers.
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", MODE="0660", TAG+="uaccess"'

if [ -f "$UDEV_RULE" ] && [ "$(cat "$UDEV_RULE")" = "$RULE_CONTENT" ]; then
    ok "udev rule already current"
else
    echo "  this step needs sudo (writing $UDEV_RULE)"
    printf '%s\n' "$RULE_CONTENT" | sudo tee "$UDEV_RULE" >/dev/null
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=usb
    ok "udev rule installed and reloaded"
fi

# --- 5. Desktop entry --------------------------------------------------------
step "Adding a desktop entry"
APP_DIR="$HOME/.local/share/applications"
mkdir -p "$APP_DIR"
cat > "$APP_DIR/scrcpy.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Phone Screen
Comment=Mirror and control the phone
Exec=$BIN_DIR/scrcpy
Icon=$INSTALL_DIR/scrcpy.png
Terminal=false
Categories=Utility;
EOF
update-desktop-database "$APP_DIR" 2>/dev/null || true
ok "\"Phone Screen\" added to the launcher"

# --- 6. Device check ---------------------------------------------------------
step "Checking for a connected phone"
"$BIN_DIR/adb" start-server >/dev/null 2>&1 || true
DEVICES="$("$BIN_DIR/adb" devices 2>/dev/null | awk 'NR>1 && NF' || true)"

if [ -z "$DEVICES" ]; then
    warn "no ADB device detected"
    echo
    echo "  USB debugging is almost certainly still off. On the phone:"
    echo "    1. Settings → About phone → Software information"
    echo "    2. Tap 'Build number' seven times to unlock Developer options"
    echo "    3. Settings → Developer options → enable 'USB debugging'"
    echo "    4. Replug the cable and accept the 'Allow USB debugging?' prompt"
    echo
    echo "  Keep USB tethering on — the phone can do tethering and debugging"
    echo "  at the same time, so you will not lose your internet connection."
    echo
    echo "  Then run:  ./phone-link.sh mirror"
elif echo "$DEVICES" | grep -q "unauthorized"; then
    warn "phone is connected but unauthorized"
    echo "  Unlock the phone and accept the 'Allow USB debugging?' prompt,"
    echo "  ticking 'Always allow from this computer'."
else
    ok "device ready: $(echo "$DEVICES" | head -1)"
    echo
    echo "  Start mirroring with:  ./phone-link.sh mirror"
fi

echo
echo -e "${GREEN}Setup complete.${NC}  See PHONE-LINK.md for daily usage."
