#!/bin/bash
# detect-ip.sh - Platform-aware IP detection for Docker containers

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 Auto-detecting network configuration...${NC}"

# Detect platform - simplified for container environment
if [ -f /proc/version ] && grep -q Microsoft /proc/version; then
    PLATFORM="wsl"
elif [ -f /proc/version ]; then
    PLATFORM="linux"
else
    PLATFORM="linux"  # Default to linux in container
fi

echo -e "${YELLOW}📋 Detected platform: ${GREEN}$PLATFORM${NC}"

# Function to detect network IPs based on platform
detect_network_ips() {
    if [ "$PLATFORM" = "wsl" ]; then
        # WSL specific detection
        WINDOWS_IP=$(powershell.exe -Command "
            \$adapters = Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
                \$_.IPAddress -notmatch '^127\.' -and
                \$_.IPAddress -notmatch '^169\.254\.' -and
                \$_.IPAddress -notmatch '^172\.1[6-9]\.' -and
                \$_.IPAddress -notmatch '^172\.2[0-9]\.' -and
                \$_.IPAddress -notmatch '^172\.3[0-1]\.' -and
                \$_.InterfaceAlias -notmatch 'WSL' -and
                \$_.InterfaceAlias -notmatch 'Loopback' -and
                \$_.InterfaceAlias -notmatch 'vEthernet.*WSL'
            } | Sort-Object InterfaceIndex;
            \$mainAdapter = \$adapters | Where-Object {
                \$_.InterfaceAlias -match 'Wi-Fi|Ethernet|Wireless'
            } | Select-Object -First 1;
            if (-not \$mainAdapter) {
                \$mainAdapter = \$adapters | Select-Object -First 1;
            };
            if (\$mainAdapter) {
                Write-Output \$mainAdapter.IPAddress;
            }
        " 2>/dev/null | tr -d '\r\n' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

        # Fallback to WSL gateway if PowerShell detection failed
        if [ -z "$WINDOWS_IP" ] || [ "$WINDOWS_IP" = "" ]; then
            WINDOWS_IP=$(ip route show | grep default | awk '{print $3}')
        fi

        WSL_IP=$(hostname -I | awk '{print $1}')
        HOST_IP=$WINDOWS_IP
    elif [ "$PLATFORM" = "linux" ]; then
        # Read real host IP from shared volume (generated by host script)
        if [ -f /shared/real-host-ip.txt ]; then
            HOST_IP=$(cat /shared/real-host-ip.txt)
            echo -e "${GREEN}✅ Using real host IP from file: $HOST_IP${NC}"
        else
            # Fallback: try host.docker.internal or gateway
            HOST_IP=$(getent hosts host.docker.internal | awk '{print $1}' 2>/dev/null)
            if [ -z "$HOST_IP" ]; then
                HOST_IP=$(ip route show default | awk '{print $3}' | head -1)
            fi
            echo -e "${YELLOW}⚠️  Using fallback IP: $HOST_IP${NC}"
        fi

        WINDOWS_IP=$HOST_IP
        WSL_IP=$HOST_IP
    else
        # Fallback
        HOST_IP="192.168.1.100"
        WINDOWS_IP=$HOST_IP
        WSL_IP=$HOST_IP
    fi
}

# Get current IPs based on platform
detect_network_ips

echo -e "${YELLOW}📍 Detected IPs:${NC}"
echo -e "   Host IP: ${GREEN}$HOST_IP${NC}"
if [ "$PLATFORM" = "wsl" ]; then
    echo -e "   Windows Host IP: ${GREEN}$WINDOWS_IP${NC}"
    echo -e "   WSL IP: ${GREEN}$WSL_IP${NC}"
fi

# Create or update .env file with dynamic IPs
cat > /shared/.env << EOF
# Auto-generated IP configuration - $(date)
PLATFORM=$PLATFORM
HOST_IP=$HOST_IP
WINDOWS_HOST_IP=$WINDOWS_IP
WSL_IP=$WSL_IP
NEXTCLOUD_URL=http://$HOST_IP:8090
EOF

echo -e "${BLUE}📝 Updated .env file with current IPs${NC}"

# Create IP configuration file for container use
cat > /shared/ip-config.json << EOF
{
  "platform": "$PLATFORM",
  "host_ip": "$HOST_IP",
  "windows_ip": "$WINDOWS_IP",
  "wsl_ip": "$WSL_IP",
  "trusted_domains": [
    "localhost",
    "$HOST_IP",
    "$WSL_IP",
    "$WINDOWS_IP",
    "host.docker.internal"
  ],
  "generated_at": "$(date -Iseconds)"
}
EOF

echo -e "${GREEN}✅ IP configuration completed and saved to shared volume${NC}"